### ISSUE TITLE
Buggy textwrapping on mobile

### ISSUE THREAD

**Issue by barskern** [aatxe/aaronweiss.us#1]
It's maybe a bit weird putting an issue on your personal blog, but it's not because of the content. Currently deep into your blogpost about Rust and reasoning about types, and its good! Keep up the good work!

However I have a problem when trying to read the blogpost because the text doesn't wrap correctly. The header is displaying correctly, but the main content is overflowing the edge of my screen. Hence I need to zoom out to be able to see it, and that makes it hard to read. This is probably a stylesheet related problem.

I looked through `site.css`, and on line 84 I found a missing colon. This missing colon shouldn't be the issue, but I cannot find any other _error-inducing_ lines. Hence this might be related to the issue, but I'm highly uncertain (Sorry for the lack of a link to the line of code, but I am currently on my phone and unable to create a link).

I'm using **Chrome 64.0.3282.137** on **Android 7.0.0**.

**Comment by aatxe** [comment]
Thanks for the report! Definitely not weird to me, in fact, very appreciated. :) 

I don't have an Android device to test, but I did fix the typo you pointed out. Can you test if that fixed it? Remember to clear the cache first. If not, I'll probably have to install an Android emulator to play around or something.

**Comment by barskern** [comment]
I'm glad! I will test it out now. :smile:

EDIT: I could not see a change after you updated the typo. 

It might also be a result of the way you have linebreaks in the markdown-files. Maybe if you test it in Chrome with responsive layout you'll see the same issue as me?

**Comment by barskern** [comment]
The problem only occurs on specific blogposts that contain images and code. Maybe it's because of the code blocks. Again just guessing.

**Comment by aatxe** [comment]
Ah, yeah, it is actually reproducible in desktop Chrome. That's promising. It looks like the issue is indeed the source code blocks. I've shrunk their font-size which is a sort of temporary fix (at least works on the latest post), but it's less than ideal. Of course, this is the problem with preformatted text and small displays.

**Comment by aatxe** [comment]
And code blocks are set to `white-space: pre-wrap` now, so, it should be totally fixed. 😄

**Comment by barskern** [comment]
Ah yeah, I'm familiar with the problem.. I've had troubles with preformatted text before. I usually delt with the problem by not preformatting text, but that's a nasty solution when you want to open up a file in an editor that doesn't support wrapping text on long lines.

Another solution might be to add `white-space: pre-wrap;` to code-blocks. This will cause line breaks in code, which is generally ugly..

A third solution could be to make the codeblock have a percentage width and make the user scroll horizontally within the codeblock to view the code on smaller devices. This is in my opinion a clean solution.
